"""RFC 7807 problem details — exception envelope and global handlers.

Every error response is a JSON object with at least ``type``, ``title``,
``status``, ``detail``, ``instance``. We add ``tenant_id`` and ``request_id``
to make support routing straightforward.

The handlers translate the common exception classes into ProblemDetails
responses with stable ``type`` URIs. Domain code raises ``DomainError``
subclasses; FastAPI's ``HTTPException`` is mapped through the handler too.
"""

from __future__ import annotations

from http import HTTPStatus
from typing import Any

from fastapi import FastAPI, Request, status
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from starlette.exceptions import HTTPException as StarletteHTTPException

from app.core.logging import get_logger

logger = get_logger(__name__)

PROBLEM_BASE = "https://eaip.dev/problems"


class ProblemDetails(BaseModel):
    type: str = Field(
        default=f"{PROBLEM_BASE}/about:blank",
        description="A URI reference identifying the problem type.",
    )
    title: str = Field(description="A short, human-readable summary of the problem type.")
    status: int = Field(description="The HTTP status code generated by the server.")
    detail: str | None = Field(default=None, description="Human-readable explanation.")
    instance: str | None = Field(default=None, description="URI for this specific occurrence.")
    tenant_id: str | None = Field(default=None, description="Active tenant id, when known.")
    request_id: str | None = Field(default=None, description="Correlation id for support.")
    errors: list[dict[str, Any]] | None = Field(
        default=None,
        description="Per-field validation errors when applicable.",
    )


# --- domain exception hierarchy ------------------------------------------


class DomainError(Exception):
    """Base for application-level errors. Carries an HTTP status and stable type."""

    status_code: int = status.HTTP_400_BAD_REQUEST
    title: str = "Bad request"
    type_suffix: str = "domain-error"

    def __init__(self, detail: str | None = None) -> None:
        super().__init__(detail or self.title)
        self.detail = detail


class NotFoundError(DomainError):
    status_code = status.HTTP_404_NOT_FOUND
    title = "Resource not found"
    type_suffix = "not-found"


class ConflictError(DomainError):
    status_code = status.HTTP_409_CONFLICT
    title = "Resource conflict"
    type_suffix = "conflict"


class AuthenticationError(DomainError):
    status_code = status.HTTP_401_UNAUTHORIZED
    title = "Authentication required"
    type_suffix = "unauthenticated"


class AuthorizationError(DomainError):
    status_code = status.HTTP_403_FORBIDDEN
    title = "Permission denied"
    type_suffix = "forbidden"


class RateLimitedError(DomainError):
    status_code = status.HTTP_429_TOO_MANY_REQUESTS
    title = "Rate limit exceeded"
    type_suffix = "rate-limited"

    def __init__(self, detail: str | None = None, *, retry_after: int | None = None) -> None:
        super().__init__(detail)
        self.retry_after = retry_after


class IdempotencyConflictError(DomainError):
    status_code = status.HTTP_422_UNPROCESSABLE_ENTITY
    title = "Idempotency-Key conflict"
    type_suffix = "idempotency-conflict"


# --- helpers -------------------------------------------------------------


def _request_context(request: Request) -> tuple[str | None, str | None]:
    org_id = getattr(request.state, "org_id", None)
    request_id = getattr(request.state, "request_id", None)
    return (str(org_id) if org_id else None, str(request_id) if request_id else None)


def _problem_response(
    *,
    request: Request,
    status_code: int,
    title: str,
    type_suffix: str,
    detail: str | None,
    errors: list[dict[str, Any]] | None = None,
    headers: dict[str, str] | None = None,
) -> JSONResponse:
    org_id, request_id = _request_context(request)
    body = ProblemDetails(
        type=f"{PROBLEM_BASE}/{type_suffix}",
        title=title,
        status=status_code,
        detail=detail,
        instance=str(request.url.path),
        tenant_id=org_id,
        request_id=request_id,
        errors=errors,
    )
    return JSONResponse(
        status_code=status_code,
        content=body.model_dump(exclude_none=True),
        media_type="application/problem+json",
        headers=headers,
    )


# --- handlers ------------------------------------------------------------


async def domain_error_handler(request: Request, exc: DomainError) -> JSONResponse:
    headers: dict[str, str] | None = None
    if isinstance(exc, RateLimitedError) and exc.retry_after is not None:
        headers = {"Retry-After": str(exc.retry_after)}
    return _problem_response(
        request=request,
        status_code=exc.status_code,
        title=exc.title,
        type_suffix=exc.type_suffix,
        detail=exc.detail,
        headers=headers,
    )


async def http_exception_handler(request: Request, exc: StarletteHTTPException) -> JSONResponse:
    title = HTTPStatus(exc.status_code).phrase if exc.status_code in HTTPStatus._value2member_map_ else "HTTP error"
    return _problem_response(
        request=request,
        status_code=exc.status_code,
        title=title,
        type_suffix=f"http-{exc.status_code}",
        detail=exc.detail if isinstance(exc.detail, str) else None,
        headers=getattr(exc, "headers", None),
    )


async def validation_exception_handler(
    request: Request, exc: RequestValidationError
) -> JSONResponse:
    return _problem_response(
        request=request,
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        title="Request validation failed",
        type_suffix="validation",
        detail="One or more fields failed validation.",
        errors=[
            {
                "loc": list(err["loc"]),
                "msg": err["msg"],
                "type": err["type"],
            }
            for err in exc.errors()
        ],
    )


async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    logger.exception("unhandled.exception", exc_info=exc, exception_class=type(exc).__name__)
    return _problem_response(
        request=request,
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        title="Internal server error",
        type_suffix="internal",
        detail="An unexpected error occurred.",
    )


def install_exception_handlers(app: FastAPI) -> None:
    app.add_exception_handler(DomainError, domain_error_handler)  # type: ignore[arg-type]
    app.add_exception_handler(StarletteHTTPException, http_exception_handler)
    app.add_exception_handler(RequestValidationError, validation_exception_handler)  # type: ignore[arg-type]
    app.add_exception_handler(Exception, unhandled_exception_handler)
